### ISSUE TITLE
Questions on instalation

### ISSUE THREAD

**Issue by fcabaud** [hackersandslackers/paramiko-tutorial#1]
Hello

I'm on Ubuntu 19.10 with python3.7

1) python3 main.py -> There is no main.py

2) python3 setup.py run -> error: invalid command 'run'

Thanks

**Comment by toddbirchard** [comment]
Hey @fcabaud,

**main.py** is in the root of the project - make sure you're in the project directory before running `python3 main.py`. This is recommended over running **setup.py**, which I've since removed.
