### ISSUE TITLE
Dotenv module issue

### ISSUE THREAD

**Issue by Jui1337** [hackersandslackers/paramiko-tutorial#4]
Even after running requirements.txt, program still gives error that "no module named "dotenv"

**Comment by toddbirchard** [comment]
Strange... I'm seeing `python-dotenv` in the **requirements.txt** file. Can you confirm that you're using the same version of Python to run the script as you used to install the requirements? Perhaps try this just in case:

```shell
python3 -m pip install -r requirements.txt
python3 -m main.py
```
